#!/bin/bash

# Frase del giorno
frase_del_giorno(){
	quotes=()
	quotes+=("Quann’ o’ mar è calm ogni strunz è marenaro")
	quotes+=("A Maronn t’accumpagn")
	quotes+=("Vide Napuel e po’ muore")
	quotes+=("E chiacchiere s’ ‘e pporta ‘o viento; ‘e maccarune jengheno ‘a panza")
	quotes+=("Nun sputà n’ciel ca n’facc te torna")
	quotes+=("Dicette o pappice vicino a’ noce, ramm’ o tiemp’ ca te spertose")
	quotes+=("È fernuta a zezzenella")
	chosen_quote=$( echo "${SRANDOM} % ${#quotes[@]}" | bc)
	machine_properties+=("Frase del giorno : ${quotes[${chosen_quote}]}")
}

# Define colors
BLUE=$(tput setaf 4)
LIGHT_BLUE=$(tput setaf 14)
WHITE=$(tput setaf 15)

# Define IL LOGO DEL NAPOLI
logo_napoli=(" ")
logo_napoli+=("${BLUE}           .:/oossssssssoo\:.           ${WHITE}")
logo_napoli+=("${BLUE}        ':+ssssssssssssssssss+:'        ${WHITE}")
logo_napoli+=("${BLUE}      -+ssssssssssssssssssssssss+-      ${WHITE}")
logo_napoli+=("${BLUE}    .ossssss${WHITE}.:s~szz~+~=^-:.${BLUE}ssssssoo.    ${WHITE}")
logo_napoli+=("${BLUE}   /ssssss${WHITE}/:~${LIGHT_BLUE}7JJYYJJJJJJJJ7${WHITE}~:\\${BLUE}sssssss\  ${WHITE}")
logo_napoli+=("${BLUE}  -ossss${WHITE}-:${LIGHT_BLUE}!7!${WHITE}NNNN${LIGHT_BLUE}JJJJJJ${WHITE}NNN${LIGHT_BLUE}J77${WHITE}-+-${BLUE}sssss+. ${WHITE}")
logo_napoli+=("${BLUE} /ossss${WHITE}/:${LIGHT_BLUE}JJJJ${WHITE}NNNNN${LIGHT_BLUE}!JJJJ${WHITE}NNN${LIGHT_BLUE}JJJJJ${WHITE}:\\${BLUE}ssss+\ ${WHITE}")
logo_napoli+=("${BLUE}+sssss${WHITE}-+${LIGHT_BLUE}JJJJJ${WHITE}NNN${LIGHT_BLUE}${WHITE}NNN${LIGHT_BLUE}J7JJ${WHITE}NNN${LIGHT_BLUE}JJJJJ${WHITE}^-${BLUE}ssssss+${WHITE}")
logo_napoli+=("${BLUE}ossss${WHITE}':${LIGHT_BLUE}7JJJJJ${WHITE}NNN${LIGHT_BLUE}J${WHITE}NNNN${LIGHT_BLUE}JJ${WHITE}NNN${LIGHT_BLUE}JJJJJ?${WHITE}:'${BLUE}ssssso${WHITE}")
logo_napoli+=("${BLUE}ossss${WHITE}!:${LIGHT_BLUE}?JJJJJ${WHITE}NNN${LIGHT_BLUE}JJJ${WHITE}NNN${LIGHT_BLUE}J${WHITE}NNN${LIGHT_BLUE}JJJJJJ${WHITE}:!${BLUE}ssssso${WHITE}")
logo_napoli+=("${BLUE}+ssss${WHITE}':${LIGHT_BLUE}7JJJJJ${WHITE}NNN${LIGHT_BLUE}JJJJJ${WHITE}NNN${LIGHT_BLUE}${WHITE}NN${LIGHT_BLUE}JJJJJ${WHITE}?:'${BLUE}sssss+${WHITE}")
logo_napoli+=("${BLUE}\ssss${WHITE}::${LIGHT_BLUE}JJJJJJ${WHITE}NNN${LIGHT_BLUE}JJJJJJ${WHITE}NNNN${LIGHT_BLUE}JJJJJJ${WHITE}::${BLUE}sssss/${WHITE}")
logo_napoli+=("${BLUE} .osss${WHITE}':${LIGHT_BLUE}JJJJJ${WHITE}NNN${LIGHT_BLUE}JJJJJJJJ${WHITE}NN${LIGHT_BLUE}JJJJJ${WHITE}:'${BLUE}sssss. ${WHITE}")
logo_napoli+=("${BLUE} -+sssss${WHITE}\:${LIGHT_BLUE}!??${WHITE}NNN${LIGHT_BLUE}JJJJJJJJJ${WHITE}N${LIGHT_BLUE}JJJ7${WHITE}:/${BLUE}ssssss- ${WHITE}")
logo_napoli+=("${BLUE}  \sssssss${WHITE}'o~${LIGHT_BLUE}7JJJJJJJJJJJJ?${WHITE}~:^${BLUE}sssssss/  ${WHITE}")
logo_napoli+=("${BLUE}    -+ssssss${WHITE}.:s~szz~+~=^-:.${BLUE}sssssss+-    ${WHITE}")
logo_napoli+=("${BLUE}      ':+osssssssssssssssssssso+:'      ${WHITE}")
logo_napoli+=("${BLUE}        \+osssssssssssssssssso^'        ${WHITE}")
logo_napoli+=("${BLUE}           .:/oossssssssoo/:.           ${WHITE}")
logo_napoli+=(" ")

# Find properties of the machine
user=$USER
machine=$HOSTNAME
os=$( cat /etc/os-release | grep "PRETTY_NAME=" | sed 's/["]//g' | sed 's/PRETTY_NAME=//g' )
kernel_version=$(uname -r)
shell=$( echo $SHELL | awk '{n=split($0, array, "/"); print array[n]}'  )

lscpu_output=$(lscpu)
processor=$( cat /proc/cpuinfo | grep -m 1 -i "model name" | cut -d ' ' -f 3- )
num_threads=$(nproc)
threads_per_core=$( echo "${lscpu_output}" | grep -m 1 -i "Thread(s) per core" | awk '{print $NF}')
num_cores=$((${num_threads} / ${threads_per_core}))
min_cpu_freq=$( echo "${lscpu_output}" | grep -m 1 -i "CPU min MHz" | awk '{print $NF}')
max_cpu_freq=$( echo "${lscpu_output}" | grep -m 1 -i "CPU max MHz" | awk '{print $NF}')

mem_total=$(cat /proc/meminfo | grep "MemTotal" | awk '{print $2}')
mem_total=$(echo "${mem_total} / 1000000" | bc -l)
mem_avail=$(cat /proc/meminfo | grep "MemAvailable" | awk '{print $2}')
mem_avail=$(echo "${mem_avail} / 1000000" | bc -l)
mem_perc=$(echo "${mem_avail} * 100 / ${mem_total}" | bc)

lshw_output=$( lshw -numeric -C display 2> /dev/null )
if [ "$(which nvidia-smi)" != "" ] && [ "$(which nvidia-smi)" != "\n" ]; then
	gpu_name=$(nvidia-smi | grep NVIDIA | tail -n 1 | awk '{i = 3; while($i != "On" && $i != "Off"){printf $i " "; i += 1 }; printf "\n"}')
else
	gpu_name=$(echo "${lshw_output}" | grep "product" | head -n 1 | awk '{print $2}')
fi
gpu_vendor=$(echo "${lshw_output}" | grep "vendor" | head -n 1 | awk '{$1 = ""; $NF = ""; print $0;}')

if [ $XDG_CURRENT_DESKTOP ]; then
	desktop_env=$(echo $XDG_CURRENT_DESKTOP | awk '{split($0, array, ":"); print array[2]}')
else
	desktop_env="Not implemented yet for your DE"
fi
terminal_type=$TERM

# Write the strings with the properties
machine_properties=(" " " " " ")
machine_properties+=("User : ${user}")
machine_properties+=("Machine : ${machine}")
machine_properties+=("OS : ${os}")
machine_properties+=("Kernel : ${kernel_version}")
machine_properties+=("Shell : ${shell}")
machine_properties+=("Processor : ${processor}")
machine_properties+=("Number cores/threads : ${num_cores}/${num_threads}")
machine_properties+=("$(printf 'Min CPU freq : %.0f MHz' ${min_cpu_freq})")
machine_properties+=("$(printf 'Max CPU freq : %.0f MHz' ${max_cpu_freq})")
machine_properties+=("$(printf 'Memory available/total : %.1f/%.1f GB (%d%%)' ${mem_avail} ${mem_total} ${mem_perc})")
machine_properties+=("GPU : ${gpu_name}")
machine_properties+=("GPU vendor :${gpu_vendor}")
machine_properties+=("DE : ${desktop_env}")
machine_properties+=("Terminal : ${terminal_type}")
machine_properties+=("Giocatore preferito : Maradona")
frase_del_giorno

# Pad the machine_properties array to the dimensions of logo_napoli
len_logo_napoli=${#logo_napoli[@]}
len_machine=${#machine_properties[@]}
diff=$((${len_logo_napoli} - ${len_machine}))

for i in $(seq 1 $diff); do
	machine_properties+=(" ")
done

# Print on screen
for i in $(seq 0 $(($len_logo_napoli - 1))); do
	printf "%s\t%s\n" "${logo_napoli[$i]}" "${machine_properties[$i]}"
done
